# Generated by Django 5.2.10 on 2026-01-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_clinic_created_at_alter_clinic_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='models.clinic'),
        ),
    ]
